
import Header2 from "../components/header/header2"

export const metadata = {
    title: 'TBVH | Home',
    description: 'Generated by create next app',
  }
  
  export default function HomeLayout({
    children,
  }: {
    children: React.ReactNode
  }) {

    return (
      <html lang="en" data-theme="mytheme">
        <body className="bg-white">
          <Header2 homeColor="text-primary" createColor="text-nothing" profileColor="text-nothing"/>
          {children}
        </body>
      </html>
    )
  }