import './globals.css'
import Header from './components/header/header'
import Footer from './components/footer/footer'

export const metadata = {
  title: 'TBVH | To Be Very Honest',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className="bg-white">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
