import Header2 from "../components/header/header2"

export const metadata = {
    title: 'TBVH | Home',
    description: 'Generated by create next app',
  }
  
  export default function ProfileLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en" data-theme="mytheme">
        <body className="bg-white">
          <Header2 homeColor="text-nothing" createColor="text-nothing" profileColor="text-neutral"/>
          {children}
          
        </body>
      </html>
    )
  }